git add "_f.sh" 
git add "AltaUsuariosDA/*"
git add "analizarDiscoDuro.bat"
git add "BackUp-Demo/*"
git add "borrarHistorialNavegador.bat"
git add "borrarTemporales.bat" 
git add "CDC/*" 
git add "Crear-Varios-Usuarios/*" 
git add "DirectorioActivo/*" 
git add "GuiaDCAdicionalWindows2016PowerShell.odt" 
git add "Imagenes/*" 
git add "MenusPowerShell/*" 
git add "powershell/*" 
git add "README.md" 
git add "VerEstadoBateria.bat" 
git add "WifiPassword-Demo/*"
git nota "PS 5.1"
git sube
