git add "_f.sh" 
git add "Conexión remota a controladores de dominio con PowerShell.ps1" 
git add "EjemploExamenAnteriorPowershell.pdf" 
git add "examen powershell" 
git add "GenerarRegistrosDNSconPowerShell.ps1" 
git add "Importantes" 
git add "MENU_PRINCIPAL_POWERSHELL_ASO.ps1" 
git add "menubasico.ps1" 
git add "MenuConFunciones.ps1" 
git add "MenuSimple.ps1" 
git add "menuUsuariosYGrupos.ps1" 
git add "MenuVariosPowershell.ps1" 
git add "Server_Inventory_12-16-2018.csv" 
git add "sueltos.ps1" 
git add "wmi-powershell.ps1"
git nota "examen PS"
git sube